---
- name: Install Packages Deps
  yum: name={{item}} state=present
  with_items:
       - vim
       - lsb
       - sysstat
       - dstat
       - ntp
       - dmidecode
       - acpid
  when: ansible_os_family == "RedHat"
