---
- include: tasks/deps.yml

- stat: path=/etc/kubernetes/admin.conf
  register: master_exists

- stat: path=/etc/kubernetes/kubelet.conf
  register: kubelet_exists

- command: kubeadm --api-advertise-addresses={{ ansible_enp0s3.address }}
  when: 
    - master_exists.stat == False
    - kubelet_exists.stat == False
  register: kubecl_master

- command: kubeadm join --token 026325.e7ae1a4513763910 {{ master_ip }}
  when:
    - master_exists.stat == False
    - kubelet_exists.stat == False
    - kubecl_master.stat == False
