FROM centos:6
MAINTAINER admin@{{ site }} 
ENV container docker
RUN rpm --rebuilddb \
	&& yum --setopt=tsflags=nodocs -y install \
		elinks-0.12-0.21.pre5.el6_3 \
		httpd-2.2.15-54.el6.centos
	&& rm -rf /var/cache/yum/* \
	&& yum clean all

CMD ["/bin/bash"]

