---
- include: tasks/deps.yml

- name: Apply Kernel tuning
  command: tuned-adm profile throughput-performance

- name: Create mount point
  file: state=directory path={{ mount }}

- name: Create brick mount point
  file: state=directory path={{ brick }}/{{ volume }}

- name: Partition the device ##### Carefulllllllllll
  shell: 'echo -e "o\nn\np\n1\n\n\nw" | fdisk {{ device }}'

- name: Format device
  filesystem: fstype=ext4 dev={{ device }}{{ partition }}

- name: Mount brick volume
  mount:
    name: "{{ brick }}/{{ volume }}"
    src: "{{ device }}{{ partition }}"
    fstype: ext4
    state: mounted

- name: Create Gluster volume dir
  file: state=directory path={{ brick }}/{{ volume }}/{{ vol }}

- name: Download repo conf Conf
  template: src=glusterfs-epel.repo.j2 dest=/etc/yum.repos.d/glusterfs-epel.repo

- name: Install gluster software
  yum: name=glusterfs-server enablerepo=glusterfs-epel disable_gpg_check=yes
  with_items:
     - glusterfs-server
     - glusterfs-api
     - glusterfs-cli

- name: Start Gluster Services
  service: name={{ item }} state=started enabled=yes
  with_items:
     - glusterd

- name: Probe peers
  command: gluster peer probe {{ node2 }}

- name: Create Gluster Volume
  command: "{{ item }}"
  run_once: true
  ignore_errors: yes
  with_items:
     - "gluster volume create {{ volume }} replica 2 {{ node1 }}:{{ brick }}/{{ volume }}/{{ vol }} {{ node2 }}:{{ brick }}/{{ volume }}/{{ vol }}"
     - "gluster volume start {{ volume }}"
     - "gluster volume set {{ volume }} nfs.disable on"
     - "gluster volume set {{ volume }} performance.write-behind-window-size 4MB"
     - "gluster volume set {{ volume }} performance.cache-size 256MB"
     - "gluster volume set {{ volume }} performance.io-cache on"

- name: Mount gluster volume
  mount:
    name: "{{ mount }}"
    src: "{{ ansible_bond0.ipv4.address }}:/{{ volume }}"  #### For prod this shhould be changed to ansible_default_ipv4.address 
    fstype: glusterfs
    state: mounted

