---
- name: Install Packages Deps
  apt: name={{item}} state=present
  with_items:
       - docker.io
       - haproxy
       - python-pip
       - ntp
       - dmidecode
       - acpid
  when: ansible_os_family == "Debian"

- command: pip install docker-py
