---
vc_path: "/export/apps/vc/"
#app_name: "websrv"
site: "betvictor.pt"
servername: "localhost.{{ site }}"
serveradmin: "admin@{{ site }}"
documentrootdir: "localhost.{{ site }}"
errorlog: "localhost.{{ site }}"
customlog: "localhost.{{ site }}"
lb_mode: "http"
#lb_port: "8080"
#httpd_port: "8081"
