---
- command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

- file: path=/etc/apt/sources.list.d/docker.list state=touch

- name: Set docker repo
  lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    insertafter: EOF
    line: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"

- command: apt-get update

- name: Install Packages Deps
  apt: name={{item}} state=present
  with_items:
       - docker.io
       - python-pip
       - ntp
       - dmidecode
       - acpid
       - apt-transport-https
       - ca-certificates
  when: ansible_os_family == "Debian"

- name: Docker Service
  service: name=docker state=started enabled=yes

