---
- name: Install Packages Deps
  yum: name={{item}} state=present
  with_items:
       - git
       - svn
       - httpd
       - "@High Availability"
       - "@Resilient Storage"
       - "@High Availability Management"
  when: ansible_os_family == "RedHat"